# Generated by Django 5.2.4 on 2026-09-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_notice_location_comment_noticeimage_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Optional date and time when this notice automatically expires and disappears from public listings', null=True),
        ),
    ]
