# Generated by Django 5.2.4 on 2026-09-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0004_notice_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('important', 'Important ⚡'), ('emergency', 'Emergency Alert 🚨')], default='normal', help_text='Urgency level of this notice', max_length=20),
        ),
    ]
